// Module included in the following assemblies:
//
// * administering_clusters/setting-quotas-per-project.adoc

[id='quotas-quotas-{context}']
= Quota scopes

// tag::admin_quota_scopes[]
Each quota can have an associated set of _scopes_. A quota will only
measure usage for a resource if it matches the intersection of enumerated
scopes.

Adding a scope to a quota restricts the set of resources to which that quota can
apply. Specifying a resource outside of the allowed set results in a validation
error.

[cols="3a,8a",options="header"]
|===

|Scope |Description

|*Terminating*
|Match pods where `spec.activeDeadlineSeconds >= 0`.

|*NotTerminating*
|Match pods where `spec.activeDeadlineSeconds` is `nil`.

|*BestEffort*
|Match pods that have best effort quality of service for either `*cpu*` or
`*memory*`.
ifdef::openshift-enterprise,openshift-origin[]
See the xref:../admin_guide/overcommit.adoc#qos-classes[Quality of
Service Classes] for more on committing compute resources.
endif::openshift-enterprise,openshift-origin[]

|*NotBestEffort*
|Match pods that do not have best effort quality of service for `*cpu*` and
`*memory*`.
|===

A *BestEffort* scope restricts a quota to limiting the following resources:

- `*pods*`

A *Terminating*, *NotTerminating*, and *NotBestEffort* scope restricts a quota
to tracking the following resources:

- `*pods*`
- `*memory*`
- `*requests.memory*`
- `*limits.memory*`
- `*cpu*`
- `*requests.cpu*`
- `*limits.cpu*`
- `*ephemeral-storage*`
- `*requests.ephemeral-storage*`
- `*limits.ephemeral-storage*`

[NOTE]
====
Ephemeral storage requests and limits apply only if you enabled the
ephemeral storage technology preview. This feature is
disabled by default.
====
// end::admin_quota_scopes[]
